global_costmap:
    global_frame: map
    rolling_window: false
    track_unknown_space: true
    width:                      20.0
    height:                     20.0
    origin_x:                   -3.0
    origin_y:                   -3.0

    plugins:
        - {name: static,                  type: "costmap_2d::StaticLayer"}
        - {name: inflation,               type: "costmap_2d::InflationLayer"}
